### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by RichardLitt** [orbitdb/orbit-db-feedstore#15]
There are none at the moment.

**Comment by haadcode** [comment]
The tests for the stores are in the main repo, eg https://github.com/orbitdb/orbit-db/blob/master/test/feed.test.js.

**Comment by haadcode** [comment]
@RichardLitt thanks for the issue! (and the same ones in other repos)

We test all the modules that orbitdb depends on in the [main repo]( https://github.com/orbitdb/orbit-db/blob/master/test/).

There's no plan to move them here, nor add separate tests to this repo. However, if anyone wants to move them, we should discuss it first and have a proposal how/what/where to do that as it is a massive change to the dev tooling. I'm personally not against it, but we need to understand the trade offs and workload before it makes sense to commit to moving them.

Given the above, closing this issue as wont-fix.

**Comment by RichardLitt** [comment]
Opening to note that we should add a note to the README about this.

**Comment by aphelionz** [comment]
Made a note in the README
